# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :title

# Setup
title:               'Who Is Nick?'
tagline:             'Simple question. Complex Answer.'
description:         "I've been asking myself this question for most my life. I still don't have an answer."
url:                 http://ethernick.github.io
baseurl:             ''
markdown:            kramdown
highlighter:         rouge
gems:                [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Nick Kempinski
  email:             nick@whoisnick.com

# Custom vars
navigation:
 - title:            Home
   url:              /index
 - title:            Beer
   url:              /beer
 - title:            About
   url:              /about
 - title:            Archive
   url:              /archive

social:
   github:           ethernick
   twitter:          ethernick
   facebook:         nick.kempinski
   email:            nick@whoisnick.com

google_analytics:    "UA-130582-1"
