backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    public_folder: "/assets/img"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", title: "image", widget: "image"
      - {label: "Allow Comments", name: "comments", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
    files: 
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'About' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'default' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Beer Page"
        name: "beer"
        file "beer.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Beer around the world' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'default' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
